# Generated by Django 4.2.2 on 2023-06-10 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_referencia_porcentaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='adeudo',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField(default=0)),
                ('tarjeta', models.CharField(max_length=20)),
                ('fecha', models.CharField(max_length=30)),
                ('prestamo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.prestamo')),
            ],
        ),
    ]
