# Generated by Django 4.2.2 on 2023-06-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pago_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencia',
            name='bancarias_exists',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='crediticias_exists',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='laborales_exists',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='personales_exists',
            field=models.CharField(max_length=1),
        ),
    ]
